/*pgAdmin 4*/
-- senha: 1234

-- Criando o Banco de Dados
-- Create database Teste

-- Tools - Query Tool

SHOW DATESTYLE;

-- WINDOWS/ARQUIVOS DE PROGRAMA/POSTGRESQL/DATA/POSTGRESQL.CONFIG

-- PESQUISAR POR DATESTYLE

-- COMENTAR O ANTIGO E CRIAR UM NOVO SE FOR NECESSÁRIO

-- SERVIÇOS DO WINDOWS
-- POSTGRESQL REINICIAR O SERVIÇO

-- FUNÇÕES DE AGREGAÇÃO - AGREGA E SOMA
-- QUERY SIMPLES
SELECT * FROM FUNCIONARIOS;

-- COUNT, MAX, MIN, SUM

SELECT COUNT(*) FROM FUNCIONARIOS;

SELECT COUNT(*) FROM FUNCIONARIOS
GROUP BY SEXO;

-- COLOCANDO O NOME DA COLUNA
SELECT SEXO, COUNT(*) AS QUANTIDADE FROM FUNCIONARIOS
GROUP BY SEXO;

--NUMERO DE FUNCIONARIOS DE CADA DEPARTAMENTO
SELECT DEPARTAMENTO, COUNT(*) AS QUANTIDADE
FROM FUNCIONARIOS
GROUP BY DEPARTAMENTO;

